name: Test for code vulnerabilites

on:
  push:
    branches: []
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |
          gitleaks detect --verbose -c gitleaks.toml