name: Go publish

on:
  push:
    branches: [ feature/pipeline-build-push-api-trips ]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: read

defaults:
  run:
    working-directory: apis/trips/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/devopsoh/api-trips:${{ github.sha }}
