name: Deploy api/trips

on:
  push:
    branches: [ main ]
    paths:
      - 'apis/trips/**'

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: apis/trips/
          tags: ghcr.io/devopsopenhack/devopsoh0827/devopsoh/api-trips:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az webapp config container set --docker-custom-image-name 'ghcr.io/devopsopenhack/devopsoh0827/devopsoh/api-trips:${{ github.sha }}' --name devopsoh06022trips --resource-group devopsoh06022rg --slot staging
#      - name: Deploy to Azure Web App
#        id: deploy-to-webapp
#        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
#        with:
#          app-name: ${{ env.AZURE_WEBAPP_NAME }}
#          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#          images: 'ghcr.io/devopsopenhack/devopsoh0827/devopsoh/api-trips:${{ github.sha }}'
