on:
  push:
    branches: [ main ]

env:
  TFSTATE_STORAGE_ACCOUNT_NAME: ${{ secrets.TFSTATE_STORAGE_ACCOUNT_NAME }}
  TFSTATE_STORAGE_CONTAINER_NAME: ${{ secrets.TFSTATE_STORAGE_CONTAINER_NAME }}
  TFSTATE_KEY: ${{ secrets.TFSTATE_KEY }}
  TFSTATE_RESOURCES_GROUP_NAME: ${{ secrets.TFSTATE_RESOURCES_GROUP_NAME }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}

jobs:
  getResourcePrefix:
    name: "Get resource prefix"
    runs-on: ubuntu-latest
    outputs:
      # Set output for next job
      RESOURCES_PREFIX: ${{ steps.resources_prefix.outputs.result }}
    steps:
      # Get RESOURCES_PREFIX based on the repo name
      - name: Get repo name
        uses: actions/github-script@v5
        id: resources_prefix
        with:
          result-encoding: string
          script: return context.repo.repo.toLowerCase()

  validate:
    name: "Validate"
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          cd iac/terraform
          chmod u+x deploy.sh
          ./deploy.sh -l westeurope -c validate

  deploy:
    name: "Deployment"
    runs-on: ubuntu-latest
    environment: "production"
    needs: "validate"
    steps:
      - shell: bash
        run: |
          cd iac/terraform
          chmod u+x deploy.sh
          ./deploy.sh -l westeurope -c deploy
        